name: Add NONG Song
description: Add a NONG song to NONG index.
title: "Add NONG Song: "
labels:
  - "nong-addition"
  - "official-addition"
body:
  - type: input
    id: song-name
    attributes:
      label: Song Name
      description: What is the name of the song?
      placeholder: ex. Lost (XVA Remix)
    validations:
      required: true
  - type: input
    id: artist-name
    attributes:
      label: Artist Name
      description: Who is the artist of the song?
      placeholder: ex. CRIM3S
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Where should the song be sourced from?
      options:
        - YouTube
        - Direct file download
      default: 0
    validations:
      required: true
  - type: input
    id: youtube-link
    attributes:
      label: YouTube Link
      description: If you chose YouTube, what is the URL of the video?
      placeholder: Ex. https://www.youtube.com/watch?v=VZXeoUPPFOY
  - type: input
    id: direct-link
    attributes:
      label: Direct File Link
      description: If you chose Direct file download, what is the URL of the file? Must be a link to a proper CDN, not Google Drive, Dropbox, or MediaFire.
      placeholder: Ex. https://www.example.com/song.mp3
  - type: input
    id: song-id
    attributes:
      label: Song ID
      description: Which song ID should the NONG song replace in Geometry Dash?
      placeholder: Ex. 945695
    validations:
      required: true
  - type: input
    id: start-offset
    attributes:
      label: Start Offset [ms]
      description: What is the start offset of the song in milliseconds?
      placeholder: Ex. 0
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Extra
      description: Anything else you would like to add? For example, levels that use that song.
      placeholder: Ex. Used in the level "Slaughterhouse" - 27690100
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for contributing to the NONG index!"
