name: Compress JSON files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress-json:
    runs-on: ubuntu-latest

    steps:
    - name: Debounce 30 seconds
      uses: zachary95/github-actions-debounce@v0.1.0  # <- Update this to use latest package versions
      with:
        wait: 30

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compress JSON files and push to separate branch
      if: steps.check-commits.outputs.NEW_COMMITS == ${{ github.sha }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch origin
        git checkout origin/dist
        git checkout -b dist-edit
        git rm -r . || true
        git checkout main -- '*.json'
        git checkout origin/dist -- 'sfh-rooot.json.gz' || true
        git checkout origin/dist -- 'sfh-pingusmc.json.gz' || true
        git checkout origin/dist -- 'sfh-yt.json.gz' || true
        git checkout origin/dist -- 'sfh.json.gz' || true
        find . -name "*.json" -exec gzip {} \;
        git add .
        git commit --allow-empty -m "update dist to json at $(git log --pretty=format:"%h" -n 1)"
        git push origin dist-edit:dist
